name: Publish App

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "public/**"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          local-dir: "build/"
          log-level: minimal
